[package]
name = "remon-server"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base32 = "0.5.0"
base64 = "0.22.1"
chrono = "0.4.38"
config = "0.14"
fast_qr = "0.13.1"
axum = "0.8.8"
tower = "0.5.2"
tower-http = { version = "0.5", features = ["trace", "compression-gzip"] }
jsonwebtoken = { version = "10.2.0", features = ["rust_crypto"]}
reqwest = "0.12"
ring = "0.17.14"
serde = { version = "1.0.202", features = ["derive"] }
serde_derive = "1.0.228"
serde_json = "1.0.117"
thiserror = "2.0.17"
sqlx = { version = "0.7.4", features = ["sqlite", "runtime-tokio"] }
sysinfo = "0.30.12"
totp-rs = "5.5.1"
env_logger = "0.11.3"
log = "0.4.21"
local-ip-address = "0.6.1"
blake3 = "1.5.1"
maplit = "1.0.2"
fcm = { git = "https://github.com/rj76/fcm-rust.git" , rev = "cd7323ce" }
strum = "0.27.2"
strum_macros = "0.27.2"
tokio = { version = "1.49.0", features = ["full"] }
tonic = "0.11.0"
tonic-reflection = "0.11.0"
prost = "0.12.6"
colored = "3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[build-dependencies]
tonic-build = "0.11.0"

[dev-dependencies]
ctor = "0.6.3"
