name: "Build and test app"
description: "Build and test app on different platforms"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: ⚡ Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: 🔨 Build
      shell: bash
      env:
        REMON__AUTH__JWT_SECRET: "ci-test-secret-minimum-32-characters-long-12345678"
      run: cargo build --release --all-features

    - name: 🔎 Test
      shell: bash
      env:
        REMON__AUTH__JWT_SECRET: "ci-test-secret-minimum-32-characters-long-12345678"
      run: cargo test --release
