# a composite action, as described here:
# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: "Build and test app"
description: "Build and test app on different platforms"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: ⚡ Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install protoc compiler
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

    - name: 🔨 Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features

    - name: 🔎 Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release

    # https://stackoverflow.com/a/64702025/12555423
    # these will be used once we add integration tests
    # - name: ⚙ Integration test
    #   uses: actions-rs/cargo@v1
    #   with:
    #     command: test
    #     args: --release --features "integration_tests"
