name: "Build and test app"
description: "Build and test app on different platforms"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: ⚡ Cache
      uses: Swatinem/rust-cache@v2

    - name: Format
      shell: bash
      run: cargo fmt --all -- --check

    - name: Clippy
      shell: bash
      env:
        REMON__AUTH__JWT_SECRET: "ci-test-secret-minimum-32-characters-long-12345678"
      run: cargo clippy --all-targets --all-features

    - name: Build
      shell: bash
      env:
        REMON__AUTH__JWT_SECRET: "ci-test-secret-minimum-32-characters-long-12345678"
      run: cargo build --release --all-features

    - name: Test
      shell: bash
      env:
        REMON__AUTH__JWT_SECRET: "ci-test-secret-minimum-32-characters-long-12345678"
      run: cargo test --release
