on: [push]

name: CI for push

jobs:
  build_and_test_ubuntu:
    name: Build and test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and test on ubuntu
        uses: ./.github/build-and-test
