on: [pull_request]

name: CI for pull requests

jobs:
  build_and_test_ubuntu:
    name: Build and test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: build_and_test
        uses: ./.github/build-and-test

  build_and_test_windows:
    name: Build and test on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - id: build_and_test
        uses: ./.github/build-and-test

  # https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md
  build_and_test_macos_x86_64:
    name: Build and test on macOS
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - id: build_and_test
        uses: ./.github/build-and-test

  # https://github.com/actions/runner-images/blob/main/images/macos/macos-13-arm64-Readme.md
  build_and_test_macos_arm64:
    name: Build and test on macOS
    runs-on: macos-13-arm64
    steps:
      - uses: actions/checkout@v4
      - id: build_and_test
        uses: ./.github/build-and-test
